# Setup
title:               ABC Documentation
tagline:             'Testing a theme'
description:         'A help system for our products.'
url:                 
baseurl:             /blog/
paginate:            5
permalink:           pretty

docs_list_title: ABC Documentation
docs:

- title: About This Guide
  url: about this guide.md

- title: Installation
  url: installation.md

- title: Run ABC App
  url: Run ABC app.md
  
# About/contact
author:
  name:              Jisha George
  url:               
  email:             jisha.george@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
