# Setup
title:               ABC Documentation
tagline:             'Testing a Jekyll theme'
description:         'A help system for our products.'
url:                 
baseurl:             /blog/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jisha George
  url:               
  email:             jisha.george@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
